Feature
Artofpaganini/Fragment-Android- pull request #1
Opened 2020-09-09 11:52 UTC by Artofpaganini

Added EditText, realized TextWatcher and OnClickLister + make the checking  field by null and spaces

2020-09-09 15:33 UTC, Akvit commented
фичёвую ветку надо в дев вливать

- [ ] исправить

2020-09-09 15:57 UTC, Akvit requested changes

2020-09-09 15:57 UTC, Akvit commented on app/proguard-rules.pro
> +#   http://developer.android.com/guide/developing/tools/proguard.html
изучи гит игнор. это в репозитории не нужно

- [ ] изучить гит игнор

2020-09-09 15:57 UTC, Akvit commented on app/src/main/res/layout/activity_main.xml
> +    <fragment
Как правило, вместо fragment используют FragmeLayout

2020-09-09 15:57 UTC, Akvit commented on gradle.properties
> +# http://www.gradle.org/docs/current/userguide/build_environment.html
Гит игнор

- [ ] гит игнор

2020-09-09 15:57 UTC, Akvit commented on gradlew
> +while [ -h "$PRG" ] ; do
это всё мусор для репозитория. студия сама такие файлы генерирует

- [ ] гитигнор

2020-09-09 15:57 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/MainActivity.java
> +
Я говорил про клик на enter, а не на edit text

- [ ] ?

2020-09-09 15:57 UTC, Akvit commented on app/src/main/java/by/andersen/intern/dobrov/MainActivity.java
> +        if (!checkStringFieldByZero()) {
и почему просто if else нельзя?

- [ ] ?

2020-09-09 16:00 UTC, Akvit commented
Напиши в названии фичи номер задачи

- [ ] написал

2020-09-10 06:21 UTC, Artofpaganini commented on app/src/main/res/layout/activity_main.xml
> +    <fragment
Исправил!

2020-09-10 06:22 UTC, Artofpaganini commented on gradle.properties
> +# http://www.gradle.org/docs/current/userguide/build_environment.html
Исправил!

2020-09-10 06:23 UTC, Artofpaganini commented on gradlew
> +while [ -h "$PRG" ] ; do
Исправил!

2020-09-10 07:06 UTC, Artofpaganini commented on app/src/main/java/by/andersen/intern/dobrov/MainActivity.java
> +        if (!checkStringFieldByZero()) {
декомпозиция

2020-09-10 07:16 UTC, Akvit commented
> фичёвую ветку надо в дев вливать
> 
> * [x]  исправить



> фичёвую ветку надо в дев вливать
> 
> * [x]  исправить

Всё на мастер смотрит
![image](https://user-images.githubusercontent.com/17576565/92693743-afc2cf80-f34e-11ea-817f-75d171210810.png)

2020-09-10 08:33 UTC, closed without merging